# Generated by Django 3.1 on 2022-10-24 03:38

from django.db import migrations
import store.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=store.fields.SecureSlugField(max_length=200, unique=True),
        ),
    ]
