# Generated by Django 3.1 on 2022-10-24 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', store.fields.SecureCharField(max_length=20)),
                ('first_name', store.fields.SecureCharField(max_length=50)),
                ('last_name', store.fields.SecureCharField(max_length=50)),
                ('phone', store.fields.SecureCharField(max_length=15)),
                ('email', store.fields.SecureEmailField(max_length=50)),
                ('address_line_1', store.fields.SecureCharField(max_length=50)),
                ('address_line_2', store.fields.SecureCharField(blank=True, max_length=50)),
                ('country', store.fields.SecureCharField(max_length=50)),
                ('state', store.fields.SecureCharField(max_length=50)),
                ('city', store.fields.SecureCharField(max_length=50)),
                ('order_note', store.fields.SecureCharField(blank=True, max_length=100)),
                ('order_total', store.fields.SecureFloatField()),
                ('tax', store.fields.SecureFloatField()),
                ('status', store.fields.SecureCharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='New', max_length=10)),
                ('ip', store.fields.SecureCharField(blank=True, max_length=20)),
                ('is_ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', store.fields.SecureCharField(max_length=100)),
                ('payment_method', store.fields.SecureCharField(max_length=100)),
                ('amount_paid', store.fields.SecureCharField(max_length=100)),
                ('status', store.fields.SecureCharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', store.fields.SecureIntegerField()),
                ('product_price', store.fields.SecureFloatField()),
                ('ordered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variations', models.ManyToManyField(blank=True, to='store.Variation')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
